### PR TITLE
Test timers

### PR DESCRIPTION
**Pull request by maanst**
The order of the tests is unclear to me. Changes I have done in the code are not reflected in the workflow runs. Trying to merge this branch into the main to see if anything changes.

### CODE REVIEW

**Comment by matuskalas** [comment]
Were the changes reflected after you merged this into `main`?

**Comment by maanst** [comment]
I'm a little unsure of what you mean. There might be some weird artifacts since I squashed and merged. I did this because there were many trials and errors before I figured out the problem with the hardcoded repo reference in the yamls.

**Comment by maanst** [comment]
> The order of the tests is unclear to me. Changes I have done in the code are not reflected in the workflow runs. Trying to merge this branch into the main to see if anything changes

This problem was fixed when I changed the actions/checkout to use default repo where the workflow has been started from  and not the hardcoded `edamontology/caseologue` :)

**Comment by matuskalas** [comment]
Ok, perfect👍🏽 That's what I hoped

**Pull request merged**
